/* Synthetic GPU-plane writer shared by PE NVENC tests. Only a 16-byte color
 * constant crosses from CPU; raw images are generated by the GPU shader. */
#include <d3dcompiler.h>
struct nv12_fixture {
    ID3D11VertexShader *vertex;
    ID3D11PixelShader *pixels[2];
};
static void nv12_fixture_close(struct nv12_fixture *s)
{
    if (s->vertex) ID3D11VertexShader_Release(s->vertex);
    for (unsigned i = 0; i < 2; ++i) if (s->pixels[i]) ID3D11PixelShader_Release(s->pixels[i]);
}
static HRESULT nv12_fixture_draw(struct nv12_fixture *s, ID3D11Device *device,
    ID3D11DeviceContext *context, ID3D11RenderTargetView **targets, const float *color)
{
    const char shader[] =
        "cbuffer Color:register(b0){float4 rgb;}"
        "float4 vs(uint id:SV_VertexID):SV_Position{float2 p=float2((id<<1)&2,id&2);"
        "return float4(p*float2(2,-2)+float2(-1,1),0,1);}"
        "float4 y():SV_Target{return float4((16+219*dot(rgb.xyz,float3(.2126,.7152,.0722)))/255,0,0,1);}"
        "float4 uv():SV_Target{return float4((128+224*dot(rgb.xyz,float3(-.114572,-.385428,.5)))/255,"
        "(128+224*dot(rgb.xyz,float3(.5,-.454153,-.045847)))/255,0,1);}";
    ID3DBlob *code = NULL, *errors = NULL;
    ID3D11Buffer *constants = NULL;
    HRESULT result = E_FAIL;
#define FIXTURE_CHECK(call) do { result = (call); if (FAILED(result)) goto done; } while (0)
    if (!s->vertex) {
        FIXTURE_CHECK(D3DCompile(shader, sizeof(shader)-1, NULL, NULL, NULL, "vs", "vs_4_0", 0, 0, &code, &errors));
        FIXTURE_CHECK(ID3D11Device_CreateVertexShader(device, ID3D10Blob_GetBufferPointer(code),
            ID3D10Blob_GetBufferSize(code), NULL, &s->vertex));
        ID3D10Blob_Release(code); code = NULL;
        if (errors) { ID3D10Blob_Release(errors); errors = NULL; }
    }
    for (unsigned i = 0; i < 2; ++i) if (!s->pixels[i]) {
        FIXTURE_CHECK(D3DCompile(shader, sizeof(shader)-1, NULL, NULL, NULL, i ? "uv" : "y", "ps_4_0", 0, 0, &code, &errors));
        FIXTURE_CHECK(ID3D11Device_CreatePixelShader(device, ID3D10Blob_GetBufferPointer(code),
            ID3D10Blob_GetBufferSize(code), NULL, &s->pixels[i]));
        ID3D10Blob_Release(code); code = NULL;
        if (errors) { ID3D10Blob_Release(errors); errors = NULL; }
    }
    D3D11_BUFFER_DESC desc = {.ByteWidth = 16, .Usage = D3D11_USAGE_IMMUTABLE, .BindFlags = D3D11_BIND_CONSTANT_BUFFER};
    D3D11_SUBRESOURCE_DATA data = {.pSysMem = color};
    FIXTURE_CHECK(ID3D11Device_CreateBuffer(device, &desc, &data, &constants));
    ID3D11DeviceContext_PSSetConstantBuffers(context, 0, 1, &constants);
    ID3D11DeviceContext_IASetPrimitiveTopology(context, D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
    ID3D11DeviceContext_VSSetShader(context, s->vertex, NULL, 0);
    for (unsigned i = 0; i < 2; ++i) {
        D3D11_VIEWPORT viewport = {0, 0, i ? 320 : 640, i ? 180 : 360, 0, 1};
        ID3D11DeviceContext_RSSetViewports(context, 1, &viewport);
        ID3D11DeviceContext_PSSetShader(context, s->pixels[i], NULL, 0);
        ID3D11DeviceContext_OMSetRenderTargets(context, 1, &targets[i], NULL);
        ID3D11DeviceContext_Draw(context, 3, 0);
    }
    ID3D11RenderTargetView *no_target = NULL;
    ID3D11Buffer *no_constants = NULL;
    ID3D11DeviceContext_OMSetRenderTargets(context, 1, &no_target, NULL);
    ID3D11DeviceContext_PSSetConstantBuffers(context, 0, 1, &no_constants);
    result = S_OK;
done:
    if (constants) ID3D11Buffer_Release(constants);
    if (code) ID3D10Blob_Release(code);
    if (errors) ID3D10Blob_Release(errors);
    return result;
#undef FIXTURE_CHECK
}
